dist: xenial
language: python
python: 3.7

# command to install dependencies
install:
  - pip install -r requirements.txt

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me
notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev

# command to run tests
script:
  - mypy src/main.py
  - python src/test.py
